### ISSUE TITLE
(standard_in) 1: syntax error

### ISSUE THREAD

**Issue by Oxicode** [babarot/httpstat#2]
![image](https://user-images.githubusercontent.com/1320709/37478237-aa8848c6-2847-11e8-87e4-caf628e65694.png)

**Comment by babarot** [comment]
Do you use latest version?

**Comment by babarot** [comment]
I think this problem was already fixed at https://github.com/b4b4r07/httpstat/commit/6bcc1ef7298d9428af7abd241a4762a369c238e6

**Comment by babarot** [comment]
No response, so I closed this issue. If you still have any problems, please feel free to reopen it.
